spring:
    profiles: dev
    activemq:
#      in-memory: true
#      pooled: false
      #http://activemq.apache.org/how-can-i-support-auto-reconnection.html
      broker-url: failover:tcp://localhost:61616
      user: user
      password: pass
      